language: node_js
node_js:
  - "8"

os: osx

before_install:
  - npm install -g vuepress

install:
  - npm install
  - npm run build
  - npm publish

branches:
  only:
    - master

deploy:
  provider: npm
  email: "wangjia_1919@163.com"
  api_key: ${NPM_TOKEN}
  on:
    branch: master
