os:
  - osx
  - linux
  - windows

language: nodejs
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - npm install -g vuepress

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  - provider: npm
    email: "wangjia_1919@163.com"
    skip_cleanup: true
    api_key: ${NPM_TOKEN}
    on:
      branch: master
      tags: true
    tag: latest

  - provider: npm
    email: "wangjia_1919@163.com"
    skip_cleanup: true
    api_key: ${NPM_TOKEN}
    on:
      branch: next
      tags: true
    tag: next
