language: node_js
node_js:
  - "8"

os: osx

branches:
  only:
    - master

before_install:
  - npm install -g codecov
  - npm install -g vuepress

install:
  - npm install

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "wangjia_1919@163.com"
  skip_cleanup: true
  api_key: ${NPM_TOKEN}
  on:
    branch: master
    tags: true
  tag: next
